ElasticNet:
  alpha: 0.1
  l1_ratio: 0.2

RandomForestRegression:
  n_estimators: 100
  random_state: 0

KNNRegression:
  n_neighbors: 5

XGboostRegression:
  objective: reg:squarederror
  learning_rate: 0.1
  n_estimators: 100
  max_depth: 6
  min_child_weight: 1
  subsample: 1.0
  colsample_bytree: 1.0
  colsample_bylevel: 1.0
  gamma: 0
  reg_alpha: 0
  reg_lambda: 1
  scale_pos_weight: 1
