artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/01_data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  local_data_file: artifacts/01_data_ingestion/data.zip
  unzip_dir: artifacts/01_data_ingestion

data_validation:
  root_dir: artifacts/02_data_validation
  unzip_data_dir: artifacts/01_data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/02_data_validation/status.txt

data_transformation:
  root_dir: artifacts/03_data_transformation
  data_path: artifacts/01_data_ingestion/winequality-red.csv
  test_split_percentage: 0.3

model_trainer:
  root_dir: artifacts/04_model_trainer
  train_data_path: artifacts/03_data_transformation/train.csv
  test_data_path: artifacts/03_data_transformation/test.csv
  model_name: XGboostRegression #CHANGE MODEL NAME ACCORDINGLY WITH THE params.yaml
  model_output: model.joblib

model_evaluation:
  root_dir: artifacts/05_model_evaluation
  test_data_path: artifacts/03_data_transformation/test.csv
  model_path: artifacts/04_model_trainer/model.joblib
  metric_file_name: artifacts/05_model_evaluation/metrics.json
